# Generated by Django 2.2.3 on 2022-10-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField(editable=False)),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
