# Generated by Django 2.2.3 on 2022-10-11 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='modificado',
        ),
        migrations.AlterField(
            model_name='nota',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
