# Generated by Django 2.2.3 on 2022-10-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_auto_20221010_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='creado',
            new_name='actualizado',
        ),
    ]
