# Generated by Django 2.2.3 on 2022-10-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_auto_20221010_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='color',
            field=models.CharField(default='verde', max_length=50),
        ),
    ]
