# Generated by Django 2.2.3 on 2022-10-12 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_auto_20221012_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='actualizado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
