# Generated by Django 2.2.3 on 2022-10-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_auto_20221012_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
