# Generated by Django 3.2 on 2022-07-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20220722_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacunas',
            new_name='Vacuna',
        ),
    ]
