# Generated by Django 3.2 on 2022-07-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.TextField(null=True, verbose_name='Genero'),
        ),
    ]
