# Generated by Django 2.2.3 on 2022-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock'},
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(to='Libros.Categoria'),
        ),
    ]
