# Generated by Django 2.2.3 on 2022-10-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_auto_20221004_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
