# Generated by Django 2.2.3 on 2022-10-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_carrito_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(default='nulo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
