# Generated by Django 2.2.3 on 2022-10-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0005_auto_20221008_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cuenta',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
