# Generated by Django 3.2 on 2022-07-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Generossadas',
            },
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name_plural': 'Peliculas'},
        ),
        migrations.DeleteModel(
            name='generos',
        ),
        migrations.AddField(
            model_name='genero',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula'),
        ),
    ]
