# Generated by Django 3.2 on 2022-07-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_alter_genero_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(null=True, upload_to='peliculas/portadas/', verbose_name='Imagen'),
        ),
    ]
