# Generated by Django 3.2 on 2022-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_alter_pelicula_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/portadas/', verbose_name='Imagen'),
        ),
    ]
