# Generated by Django 3.2 on 2022-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_alter_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
